### ISSUE TITLE
The requested service provider could not be loaded or initialized.

### ISSUE THREAD

**Issue by Abdulrahmanh95** [spatie/browsershot#321] opened 2019-07-26 19:11 UTC
Exit Code: -2147483645(Unknown error)

Output:
================

Error Output:
================
socket: (10106) The requested service provider could not be loaded or initialized.

Environment:
Windows 10.
Node v12.4.0.

**Comment by Abdulrahmanh95** [comment] 2019-07-27 13:13
Okay, for anyone who will see this comment.

I managed to solve it firstly by using apache server like XAMPP **NOT** Laravel artisan on command line.

After that, another problem appeared which is **Maximum execution time of 30 seconds exceeded** and this is solved by opening `httpd-xampp.conf` file and remove `SetEnv TMP "\\xampp\\tmp"` line.

But I don't know what are side effects.

**Comment by atymic** [comment] 2019-07-29 01:10
Glad you got it fixed. Please close the issue since the problem is solved (and not related to the package) :)

**Closed** 2019-07-29 06:02 UTC
